# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f1f82128de7dc2694be232722e0788bb92a733ab409fbb652d59fc6a44d2b88926003683d11aaaad876673a71c110d0c8e559e14b2bd6d42fb73f5438c7ac38

test:
  secret_key_base: 6ba1065edeaac9d7470d83c67d9f766891becfdf0bddee5131bde541445e0046490378ffee5679bd905faa84589168a9d48119d3c3ef4b206c2653aacea75863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
